"""Centralized runtime configuration facade.

This module exposes configuration and constants through a single import surface
while preserving the existing runtime behavior from the legacy implementation.
"""

from dataclasses import dataclass

import legacy_app as legacy


@dataclass(frozen=True)
class GenerationProfile:
    """Generation profile settings used by providers."""

    name: str
    num_predict: int
    max_context_chars: int
    history_turns: int


BASE_DIR = legacy.BASE_DIR
DATA_DIR = legacy.DATA_DIR
UPLOAD_DIR = legacy.UPLOAD_DIR
CHROMA_DIR = legacy.CHROMA_DIR
HISTORY_FILE = legacy.HISTORY_FILE
HISTORY_DB_FILE = legacy.HISTORY_DB_FILE

OLLAMA_BASE_URL = legacy.OLLAMA_BASE_URL
MODEL_NAME = legacy.MODEL_NAME
CHAT_MODEL_OPTIONS = legacy.CHAT_MODEL_OPTIONS
EMBEDDING_MODEL = legacy.EMBEDDING_MODEL

MAX_CHUNK_SIZE = legacy.MAX_CHUNK_SIZE
CHUNK_OVERLAP = legacy.CHUNK_OVERLAP
PARENT_CHUNK_SIZE = legacy.PARENT_CHUNK_SIZE
PARENT_CHUNK_OVERLAP = legacy.PARENT_CHUNK_OVERLAP
PARENT_WINDOW_CHILD_SPAN = legacy.PARENT_WINDOW_CHILD_SPAN

EMBED_BATCH_SIZE = legacy.EMBED_BATCH_SIZE
EMBED_LEGACY_WORKERS = legacy.EMBED_LEGACY_WORKERS
EMBED_NUM_CTX = legacy.EMBED_NUM_CTX
MAX_EMBED_NUM_CTX = legacy.MAX_EMBED_NUM_CTX
EMBED_CHARS_PER_TOKEN = legacy.EMBED_CHARS_PER_TOKEN
CHROMA_ADD_BATCH_SIZE = legacy.CHROMA_ADD_BATCH_SIZE

MAX_CONTEXT_CHARS = legacy.MAX_CONTEXT_CHARS
DEFAULT_TOP_K = legacy.DEFAULT_TOP_K
RETRIEVAL_MAX_DISTANCE = legacy.RETRIEVAL_MAX_DISTANCE
MIN_RETRIEVAL_RESULTS = legacy.MIN_RETRIEVAL_RESULTS

CHAT_TEMPERATURE = legacy.CHAT_TEMPERATURE
CHAT_TOP_P = legacy.CHAT_TOP_P
CHAT_NUM_PREDICT = legacy.CHAT_NUM_PREDICT
CHAT_KEEP_ALIVE = legacy.CHAT_KEEP_ALIVE
CHAT_REQUEST_TIMEOUT_SEC = legacy.CHAT_REQUEST_TIMEOUT_SEC
CHAT_HISTORY_TURNS = legacy.CHAT_HISTORY_TURNS

LOCAL_CHAT_NUM_PREDICT = legacy.LOCAL_CHAT_NUM_PREDICT
LOCAL_MAX_CONTEXT_CHARS = legacy.LOCAL_MAX_CONTEXT_CHARS
LOCAL_CHAT_HISTORY_TURNS = legacy.LOCAL_CHAT_HISTORY_TURNS

API_CHAT_NUM_PREDICT = legacy.API_CHAT_NUM_PREDICT
API_MAX_CONTEXT_CHARS = legacy.API_MAX_CONTEXT_CHARS
API_CHAT_HISTORY_TURNS = legacy.API_CHAT_HISTORY_TURNS

MAX_HISTORY_ITEMS = legacy.MAX_HISTORY_ITEMS
DOC_SNIPPET_CHARS = legacy.DOC_SNIPPET_CHARS
INDEX_MAX_CHUNKS = legacy.INDEX_MAX_CHUNKS
MAX_UPLOAD_MB = legacy.MAX_UPLOAD_MB
MAX_UPLOAD_BYTES = legacy.MAX_UPLOAD_BYTES
UPLOAD_STREAM_CHUNK_SIZE = legacy.UPLOAD_STREAM_CHUNK_SIZE

COLLECTION_NAME = legacy.COLLECTION_NAME
CHAT_COLLECTION_PREFIX = legacy.CHAT_COLLECTION_PREFIX
INDEX_SCHEMA_VERSION = legacy.INDEX_SCHEMA_VERSION

GEMINI_MODELS = legacy.GEMINI_MODELS
CLAUDE_MODELS = legacy.CLAUDE_MODELS
CHATGPT_MODELS = legacy.CHATGPT_MODELS
API_PROVIDERS = legacy.API_PROVIDERS

LOCAL_GENERATION_PROFILE = GenerationProfile(
    name=legacy.LOCAL_GENERATION_PROFILE.name,
    num_predict=legacy.LOCAL_GENERATION_PROFILE.num_predict,
    max_context_chars=legacy.LOCAL_GENERATION_PROFILE.max_context_chars,
    history_turns=legacy.LOCAL_GENERATION_PROFILE.history_turns,
)

API_GENERATION_PROFILE = GenerationProfile(
    name=legacy.API_GENERATION_PROFILE.name,
    num_predict=legacy.API_GENERATION_PROFILE.num_predict,
    max_context_chars=legacy.API_GENERATION_PROFILE.max_context_chars,
    history_turns=legacy.API_GENERATION_PROFILE.history_turns,
)
